[package]
name = "fractal-generation-rust"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "fractalgif"
path = "src/main.rs"


[dependencies]
image = "0.24"
num-complex = "0.4"
gif = "0.13"
eframe = "0.29"
egui = "0.29"
rand = "0.9"
svg = "0.18"
rayon = "1.7"
